# See https://www.chirpstack.io/network-server/install/config/ for a full
# configuration example and documentation.
#
# This file is for the EU868 band. See the examples/ folder for more
# configuration examples.

[postgresql]
dsn="postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable"

[redis]
url="redis://redis:6379"

[network_server]
net_id="000000"

[network_server.band]
name="KR920"

[network_server.network_settings]

  # Disable mac-commands
  #
  # When set to true, ChirpStack Network Server will not handle and / or schedule any
  # mac-commands. However, it is still possible for an external controller
  # to handle and / or schedule mac-commands. This is intended for testing
  # only.
  disable_mac_commands=false

  # Disable ADR
  #
  # When set, this globally disables ADR.
  # disable_adr=false

#  [[network_server.network_settings.extra_channels]]
#  frequency=922100000
#  min_dr=0
#  max_dr=5

#  [[network_server.network_settings.extra_channels]]
#  frequency=922300000
#  min_dr=0
#  max_dr=5

#  [[network_server.network_settings.extra_channels]]
#  frequency=922500000
#  min_dr=0
#  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922700000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=922900000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=923100000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=923300000
  min_dr=0
  max_dr=5


[network_server.gateway.backend.mqtt]
server="tcp://mosquitto:1883"

[join_server.default]
server="http://chirpstack-application-server:8003"
